# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: helloworldapp
#   labels:
#     app: helloworldapp
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: helloworldapp
#   template:
#     metadata:
#       labels:
#         app: helloworldapp
#     spec:
#       containers:
#       - name: helloworldapp
#         image: umair7865/java:latest  
#         ports:
#         - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: helloworldapp-service
#   labels:
#     app: helloworldapp
# spec:
#   selector:
#     app: helloworldapp
#   ports:
#     - protocol: TCP
#       port: 9090  # -----------------------------------------The port your Service exposes
#       targetPort: 8080  #----------------------------------- The port your container listens on
#   type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name:  ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: domain.com  #---------------------------------- Enter Your Domain Here
#       http:
#         paths:
#           - path:  /java
#             pathType: Prefix
#             backend:
#               service:
#                 name: helloworldapp-service
#                 port:
#                   number: 9090
