apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default  # ✅ Moved to default namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1     # (This is for ArgoCD)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # ArgoCD runs on HTTPS (This is for ArgoCD)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"    # Forces HTTP to HTTPS redirection even if TLS is not configured in the Ingress
spec:
  ingressClassName: nginx  # ✅ Ensures Ingress is using the correct class
  tls:
    - hosts:
        - cyberwing.info
      secretName: tls
  rules:
    - host: cyberwing.info
      http:
        paths:
          - path: /argocd(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
          - path: /umair
            pathType: Prefix
            backend:
              service:
                name: helloworldapp-service
                port:
                  number: 9090
          - path: /image
            pathType: Prefix
            backend:
              service:
                name: helloworldapp-service
                port:
                  number: 9090